name: Keep Streamlit Awake

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  ping_streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping Request
        run: curl -sI https://dynamiclinkgeneratorpy-jvrqcasnbsduy6hwwmco58.streamlit.app/ | head -n 1
