name: Keep Streamlit Awake

on:
  schedule:
    # Runs at minute 17 of every 4th hour (e.g., 4:17, 8:17) to avoid peak traffic delays
    - cron: "17 */4 * * *"
  workflow_dispatch:

jobs:
  ping_streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping Request
        run: curl -sI https://dynamiclinkgeneratorpy-jvrqcasnbsduy6hwwmco58.streamlit.app/
